### ISSUE TITLE
Candidate for gtk3-classic?

### ISSUE THREAD

**Issue by RobertZenz** [KnightMurloc/gtk-filechooser-patches#1]
There's the [gtk3-classic](https://github.com/lah7/gtk3-classic) project which tries to revert certain functionality and improve upon other. It might be interesting to get these patches into gtk3-classic, though, it's not really related to it being "classic", but might still be a nice function to have there.

**Comment by KnightMurloc** [comment]
I don't think this is a good idea. because firstly GtkFileChooserNative does not implement all the features of GtkFileChooserDialog and therefore cannot be a full replacement for it. and secondly, there are still problems with working in some applications.
